WISEroster.Mvc/Models/GcPreferenceViewModel.cs
namespace WISEroster.Mvc.Models
{
    public class GcPreferenceViewModel
    {
        public bool AllowExternalDomains { get; set; } //teacher/student emails must match GcUserEmail domain
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string GcUserEmail { get; set; }
        public string CredentialMessage { get; set; }

    }
}

WISEroster.Mvc/Controllers/AuthCallbackController.cs
using Google.Apis.Auth.OAuth2.Responses;
using Google.Apis.Auth.OAuth2.Web;
using Ninject;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using WISEroster.Business;
using WISEroster.Mvc.Classroom;
using WISEroster.Mvc.ImplementationSpecific;

namespace WISEroster.Mvc.Controllers
{
    public class AuthCallbackController : Google.Apis.Auth.OAuth2.Mvc.Controllers.AuthCallbackController
    {
        
        [Inject]
        public ISessionInfo _sessionInfo { private get; set; }

        [Inject]
        public ISetupBusiness _setupBusiness { private get; set; }


        protected override Google.Apis.Auth.OAuth2.Mvc.FlowMetadata FlowData
        {
            get { return new AppFlowMetadata(_sessionInfo.CurrentAgencyId.GetValueOrDefault(), _setupBusiness); }
        }

        [AsyncTimeout(10000)]
        public override async Task<ActionResult> IndexAsync(AuthorizationCodeResponseUrl authorizationCode,
            CancellationToken taskCancellationToken)
        {
            if (string.IsNullOrEmpty(authorizationCode.Code))
            {
                var errorResponse = new TokenErrorResponse(authorizationCode);
                Logger.Info("Received an error. The response is: {0}", errorResponse);

                return OnTokenError(errorResponse);
            }

            Logger.Debug("Received \"{0}\" code", authorizationCode.Code);

            var returnUrl = Request.Url.ToString();
            returnUrl = returnUrl.Substring(0, returnUrl.IndexOf("?"));

            //AS- make sure _ISessionInfo is initialized
            var l = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var u = _setupBusiness.GetClientEmail(l);
            //AS

            var token = await Flow.ExchangeCodeForTokenAsync(u, authorizationCode.Code, returnUrl,
                taskCancellationToken).ConfigureAwait(true);//AS-include context

            // Extract the right state.
            var oauthState = await AuthWebUtility.ExtracRedirectFromState(Flow.DataStore, u,
                authorizationCode.State).ConfigureAwait(true);//AS-include context

            return new RedirectResult(oauthState);
        }

    }
}

WISEroster.Mvc/Controllers/UserController.cs
using Google.Apis.Auth.OAuth2.Mvc;
using System;
using System.Configuration;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using WISEroster.Business;
using WISEroster.Business.Models;
using WISEroster.Domain.Models;
using WISEroster.Mvc.Classroom;
using WISEroster.Mvc.Extensions;
using WISEroster.Mvc.ImplementationSpecific;
using WISEroster.Mvc.Models;

namespace WISEroster.Mvc.Controllers
{

    public class UserController : Controller
    {

        private readonly ISessionInfo _sessionInfo;
        private readonly IOrganizationBusiness _orgBusiness;
        private readonly ISetupBusiness _setupBusiness;
     
        public UserController(IOrganizationBusiness orgBusiness, ISetupBusiness setupBusiness, ISessionInfo sessionInfo)
        {
            _orgBusiness = orgBusiness;
            _sessionInfo = sessionInfo;
            _setupBusiness = setupBusiness;
        }

       [HttpGet]
        public ActionResult Index()
        {

            var wamsUser = _sessionInfo.User;
            var agencies = wamsUser.Roles.Select(x => x.EducationOrganizationId).ToList();
            var impersonateAgencyPrivilege = ConfigurationManager.AppSettings["DPI.ImpersonateAgencyPrivilege"];
            var dpiAgencyKey = int.Parse( ConfigurationManager.AppSettings["DPI.AgencyKey"]);

            var orgs = _orgBusiness.GetEducationOrganizations(DateTime.Now.GetSchoolYear(), agencies).Select(o => new SelectableAgency { EducationOrganizationId = o.EducationOrganizationId, NameOfInstitution = o.NameOfInstitution });
            var viewModel = new ChangeAgencyViewModel { Organizations = orgs.ToList() };
            var impersonateAgencies = wamsUser.HasPrivilege(dpiAgencyKey, impersonateAgencyPrivilege);
            if (impersonateAgencies)
            {

                viewModel.AllOrganizations = _orgBusiness.GetLeas(DateTime.Now.GetSchoolYear())
                    .Select(o => new SelectableAgency { EducationOrganizationId = o.EducationOrganizationId, NameOfInstitution = o.NameOfInstitution })
                    .OrderBy(n => n.NameOfInstitution).ToList();
            }

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult ChangeAgency(int id)
        {
            _sessionInfo.SetCurrentAgency(id);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Debug()
        {

            var model = new UserDebugViewModel { EducationOrganizationId = null, Name = "null" };
            try
            {
                model.SchoolYear = DateTime.Now.GetSchoolYear();
                if (_sessionInfo != null)
                {
                    if (_sessionInfo.User != null)
                    {
                        model.Name = _sessionInfo.User.FullName;

                    }

                    if (_sessionInfo.CurrentAgencyId != null)
                    {
                        model.EducationOrganizationId = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
                    }

                    var org = _orgBusiness.GetEducationOrganization(DateTime.Now.GetSchoolYear(), 7533);
                    if (org != null)
                    {
                        model.ApiConnect = true;
                    }

                    if (_sessionInfo.User != null)
                    {
                        var agencies = _sessionInfo.User.Roles.Select(x => x.EducationOrganizationId).ToList();
                        model.Agencies = agencies;
                        var impersonateAgencyPrivilege = ConfigurationManager.AppSettings["DPI.ImpersonateAgencyPrivilege"];
                        var dpiAgencyKey = int.Parse(ConfigurationManager.AppSettings["DPI.AgencyKey"]);
                        var orgs = _orgBusiness.GetEducationOrganizations(DateTime.Now.GetSchoolYear(), agencies).Select(o => new SelectableAgency { EducationOrganizationId = o.EducationOrganizationId, NameOfInstitution = o.NameOfInstitution });
                        model.SelectableAgencies = orgs.ToList();

                        model.CanImpersonate = _sessionInfo.User.HasPrivilege(dpiAgencyKey, impersonateAgencyPrivilege);
                    }

                }
            }
            catch (Exception ex)
            {
                model.Exception = ex.ToString();
            }

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> GcPreferences(CancellationToken cancellationToken)
        {
            var edOrgId = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var pref = _setupBusiness.GetGcPreference(edOrgId);
            var model = new GcPreferenceViewModel();
            if (pref != null)
            {
                model.GcUserEmail = pref.GcUserEmail;
                model.AllowExternalDomains = pref.AllowExternalDomains;

                var cred = _setupBusiness.GetClientCredentials(edOrgId);
                if (cred != null)
                {
                    model.ClientId = cred.ClientId;
                    model.ClientSecret = cred.ClientSecret;
                    var task = await Task.Run(async () => await GcSync.TestAsync(this, edOrgId, model.GcUserEmail, _setupBusiness, cancellationToken).ConfigureAwait(true));

                    model.CredentialMessage = task.Message;
                }

            }

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> GcPreferences(GcPreferenceViewModel model, CancellationToken cancellationToken)
        {
            var edOrgId = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var pref = new OrgGcPreference
            {
                EducationOrganizationId = edOrgId,
                AllowExternalDomains = model.AllowExternalDomains,
                GcUserEmail = model.GcUserEmail
            };
            var creds = new ClientCredentials
            {
                EducationOrganizationId = edOrgId,
                ClientId = model.ClientId,
                ClientSecret = model.ClientSecret
            };

            try
            {
                _setupBusiness.UpsertGcPreference(pref);
                _setupBusiness.UpsertClientCredentials(creds);

                return RedirectToAction("ConfirmAsync","User",new{ leaId=edOrgId, userEmail=model.GcUserEmail});

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View(model);
            }
        }

        public async Task<ActionResult> ConfirmAsync(int leaId, string userEmail, CancellationToken cancellationToken)
        {
            var result = await new AuthorizationCodeMvcApp(this, new AppFlowMetadata(leaId, _setupBusiness)).
                AuthorizeAsync(userEmail,cancellationToken).ConfigureAwait(true);

            if (result.Credential != null)
            {
                return RedirectToAction("GcPreferences");
            }
            else
            {
                return new RedirectResult(result.RedirectUri);
            }
        }
    }
}

WISEroster.Mvc/Views/User/Debug.cshtml
@model WISEroster.Mvc.Models.UserDebugViewModel

@{
    ViewBag.Title = "Debug";
}

<h2>Debug</h2>

<div class="row">
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EducationOrganizationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EducationOrganizationId)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.SchoolYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SchoolYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agencies)
        </dt>

        <dd>
            @if (Model.Agencies != null)
            {
                foreach (var a in Model.Agencies)
                {
                    @Html.DisplayFor(model => a)
                    <br/>
                }
            }
            </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CanImpersonate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CanImpersonate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SelectableAgencies)
        </dt>

        <dd>
            @if (Model.Agencies != null)
            {
                foreach (var a in Model.SelectableAgencies)
                {
                    @Html.DisplayFor(model => a.NameOfInstitution)
                    <br />
                }
        }
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.ApiConnect)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApiConnect)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DbConnect)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DbConnect)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exception)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exception)
        </dd>

    </dl>
</div>

WISEroster.Mvc/Views/User/GcPreferences.cshtml
@model WISEroster.Mvc.Models.GcPreferenceViewModel
@{
    ViewBag.Title = "GcPreferences";
}
<div class="row">
    <div class="col">

        <div class="card">
            <div class="card-header bg-secondary text-white">
                <b>Google Classroom Setup/Preferences</b>
            </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {

                    <h5 class="card-subtitle  mb-2 ">Preferences</h5>
                    <div class="row">
                        <div class="col-sm-4">@Html.LabelFor(m => m.AllowExternalDomains, "Allow teachers and students from other domains")</div>
                        <div class="col-sm-1">@Html.CheckBoxFor(m => m.AllowExternalDomains)</div>
                        <div class="col-md-7">
                            Teachers and students in Google Classroom must be from the same domain as the user below by default.
                            Allowing users from external domains requires extra configuration in Google Classroom.
                        </div>
                    </div>
                    <h5 class="card-subtitle  mb-2 ">Google Classroom Credentials</h5>
                    <div class="row">
                        <div class="col">
                            <ol>
                                <li>From <a href="https://console.developers.google.com">https://console.developers.google.com</a> -> Create a new project -> 'WISERoster'</li>
                                <li>
                                    From Credentials -> Create Credentials -> OAuth client ID
                                    <ul>
                                        <li>Application type: Web application</li>
                                        <li>Name: WISERoster</li>
                                        <li>Authorized redirects URIs: @Url.Action("IndexAsync","AuthCallback", null, this.Request.Url.Scheme) </li>
                                    </ul>
                                </li>
                                <li>Download client secret json file</li>
                            </ol>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">@Html.LabelFor(m => m.ClientId, "client_id")</div>
                        <div class="col-sm-8">@Html.TextBoxFor(m => m.ClientId) <i>From client secret json</i></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">@Html.LabelFor(m => m.ClientSecret, "client_secret")</div>
                        <div class="col-sm-8">@Html.TextBoxFor(m => m.ClientSecret) <i>From client secret json</i></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">@Html.LabelFor(m => m.GcUserEmail, "Admin account")</div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.GcUserEmail)
                            <i>An admin or super admin account is required to sync data with Google Classroom</i>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-8">
                            <h5><i>  @Html.DisplayFor(m => m.CredentialMessage)</i></h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4"></div>
                        <div class="col-sm-8"><button type="submit">Save and Test</button></div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

WISEroster.Mvc/Views/User/Index.cshtml
@model WISEroster.Mvc.Models.ChangeAgencyViewModel

<table class="table table-condensed">
    <tr><th>Id</th><th>Name</th></tr>

    @foreach (var org in Model.Organizations)
    {
        <tr>
            <td>@Html.ActionLink(@org.EducationOrganizationId.ToString(), "ChangeAgency", "User", new { id = org.EducationOrganizationId },null)</td>
            <td>@Html.ActionLink(@org.NameOfInstitution, "ChangeAgency", "User", new { id = org.EducationOrganizationId }, null)</td>
        </tr>
    }
</table>

@if (Model.AllOrganizations != null)
{
<table class="table table-condensed">
    <tr><th>Id</th><th>Name</th></tr>

    @foreach (var org in Model.AllOrganizations)
    {
        <tr>
            <td>@Html.ActionLink(@org.EducationOrganizationId.ToString(), "ChangeAgency", "User", new { id = org.EducationOrganizationId },null)</td>
            <td>@Html.ActionLink(@org.NameOfInstitution, "ChangeAgency", "User", new { id = org.EducationOrganizationId },null)</td>
        </tr>
    }
</table>
}