WISEroster.Mvc/Models/SyncViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using WISEroster.Domain.Models;

namespace WISEroster.Mvc.Models
{
    public class SyncViewModel
    {
        [DisplayName("School Year")]
        [Required(ErrorMessage = "School Year is required.")]
        public short SchoolYear { get; set; }
        public List<SelectListItem> Years { get; set; }

        [DisplayName("School")]
        [Required(ErrorMessage = "School is required.")]
        public int SelectedSchool { get; set; }
        public List<SelectListItem> Schools { get; set; }


        public List<GcCourse> SyncList { get; set; }
    }
}

WISEroster.Mvc/Controllers/SyncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using WISEroster.Business;
using WISEroster.Domain.Models;
using WISEroster.Mvc.Classroom;
using WISEroster.Mvc.Extensions;
using WISEroster.Mvc.ImplementationSpecific;
using WISEroster.Mvc.Models;

namespace WISEroster.Mvc.Controllers
{
    public class SyncController : Controller
    {
        private readonly IOrganizationBusiness _orgBusiness;
        private readonly ISessionInfo _sessionInfo;
        private readonly ISetupBusiness _setupBusiness;
        private readonly IProvisioningRulesBusiness _provisioningRuleBusiness; public SyncController(IOrganizationBusiness orgBusiness, ISessionInfo sessionInfo, ISetupBusiness setupBusiness, IProvisioningRulesBusiness provisioningRuleBusiness)
        {
            _orgBusiness = orgBusiness;
            _sessionInfo = sessionInfo;
            _setupBusiness = setupBusiness;
            _provisioningRuleBusiness = provisioningRuleBusiness;
        }

        public ActionResult Preview(short? schoolYear, int? schoolId)
        {
            var model = new SyncViewModel();
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            short sy = DateTime.Now.GetSchoolYear();
            if (schoolYear == null)
            {
                if (HttpContext.Session["SchoolYear"] != null)
                {
                    schoolYear = short.Parse(HttpContext.Session["SchoolYear"].ToString());
                }
                else
                {
                    schoolYear = sy;
                }
            }
            else
            {
                HttpContext.Session["SchoolYear"] = schoolYear;
            }

            model.SchoolYear = schoolYear.GetValueOrDefault();
            model.Years = new List<SelectListItem>
            {
                new SelectListItem{Text = string.Format("{0}-{1}", sy-1, sy), Value = sy.ToString()},
                new SelectListItem{Text = string.Format("{0}-{1}", sy, sy+1), Value = (sy+1).ToString()}
            };
            model.Schools = _orgBusiness.GetSchoolsForLea(schoolYear.GetValueOrDefault(), lea, null).Select(c => new SelectListItem
            { Text = c.EducationOrganization.NameOfInstitution, Value = c.SchoolId.ToString() }).ToList();
            if (schoolId == null)
            {
                int.TryParse(model.Schools.Select(v => v.Value).FirstOrDefault(), out var school);
                schoolId = school;
            }

            model.SelectedSchool = schoolId.GetValueOrDefault();

            model.SyncList =
                _provisioningRuleBusiness.GetSyncList(lea,
                    schoolYear.GetValueOrDefault(), schoolId.GetValueOrDefault());

            return View(model);
        }


        public JsonResult ClassList(short schoolYear, int schoolId)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var syncList =
                _provisioningRuleBusiness.GetSyncList(lea,
                    schoolYear, schoolId)
                    .Select(l => new { l.SchoolYear, l.LocalCourseTitle, l.LocalCourseCode, l.SessionName, l.SectionIdentifier, l.CreateDate, l.GcName, l.GcMessage, l.Saved, l.Activated,  
                        Staff = String.Join(", ", l.GcCourseUsers.Where(u => u.IsTeacher).Select(u => u.EmailAddress)) , 
                        Student = String.Join(", ", l.GcCourseUsers.Where(u => u.IsTeacher == false).Select(u => u.EmailAddress)) });
            HttpContext.Session["SchoolYear"] = schoolYear;
            return Json(syncList);
        }

        public ActionResult Generate(short schoolYear, int selectedSchool)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();

            var saved = _provisioningRuleBusiness.GenerateSyncList(lea, schoolYear, selectedSchool);

            return RedirectToAction("Preview", new { schoolYear = schoolYear, schoolId = selectedSchool });
        }

        [HttpGet]
        public async Task<JsonResult> TestConnection(CancellationToken cancellationToken)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var gcEmail = _setupBusiness.GetClientEmail(lea);
            if (string.IsNullOrWhiteSpace(gcEmail))
            {
                return Json(new TestConnectionMessage { Connected = false, Message = "Google Classroom setup not completed" }, JsonRequestBehavior.AllowGet);
            }

            var task = await Task.Run(async () => await GcSync.TestAsync(this, lea, gcEmail, _setupBusiness, cancellationToken).ConfigureAwait(true));

            return Json(task, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> SendCourses(short schoolYear, int schoolId, bool allCourses, CancellationToken cancellationToken)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var gcEmail = _setupBusiness.GetClientEmail(lea);
            if (string.IsNullOrWhiteSpace(gcEmail))
            {
                return Json(new SyncCourseMessage { Message = "Google Classroom setup not completed" });
            }

            var syncList = _provisioningRuleBusiness.GetSyncList(lea, schoolYear, schoolId).Where(g => allCourses || !g.Saved.GetValueOrDefault()).ToList();
            var school = _orgBusiness.GetEducationOrganization(schoolYear, schoolId);

            foreach (var gcCourse in syncList)
            {
                gcCourse.AliasId = gcCourse.GcName.NameToId();
                gcCourse.Owner = "me";
            }

            var syncMessage = new SyncCourseMessage { Courses = syncList, LeaId = lea, UserEmail = gcEmail, School = school };
            var task = await Task.Run(async () => await GcSync.SendCourses(this, _setupBusiness, syncMessage, cancellationToken).ConfigureAwait(true));

            _provisioningRuleBusiness.SaveSyncProgress(lea, schoolYear, schoolId, task.Courses);
            _provisioningRuleBusiness.SaveLog(task.Logs);

            return Json(task);
        }

        [HttpPost]
        public async Task<string> SendSelectedCourse(short schoolYear, int schoolId, string classToSync, CancellationToken cancellationToken)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var gcEmail = _setupBusiness.GetClientEmail(lea);
            if (string.IsNullOrWhiteSpace(gcEmail))
            {
                return "Google Classroom setup not completed";
            }

            var gcCourse = _provisioningRuleBusiness.GetClassToSync(lea, schoolYear, schoolId, classToSync);
            var school = _orgBusiness.GetEducationOrganization(schoolYear, schoolId);

            gcCourse.AliasId = gcCourse.GcName.NameToId();
            gcCourse.Owner = "me";

            var syncMessage = new SyncCourseMessage { Courses = new List<GcCourse> { gcCourse }, LeaId = lea, UserEmail = gcEmail, School = school };
            var task = await Task.Run(async () => await GcSync.SendCourses(this, _setupBusiness, syncMessage, cancellationToken).ConfigureAwait(true));

            _provisioningRuleBusiness.SaveSyncProgress(lea, schoolYear, schoolId, task.Courses);
            _provisioningRuleBusiness.SaveLog(task.Logs);

            return task.Courses.First().GcMessage;
        }

        public async Task<JsonResult> GcList(CancellationToken cancellationToken)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var gcEmail = _setupBusiness.GetClientEmail(lea);

            var task = await Task.Run(async () => await GcSync.GetCourses(this, lea, gcEmail, _setupBusiness, cancellationToken).ConfigureAwait(true));
            return Json(task);
        }

        public async Task<ActionResult> Existing(CancellationToken cancellationToken)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var gcEmail = _setupBusiness.GetClientEmail(lea);
            var task = await Task.Run(async () => await GcSync.TestAsync(this, lea, gcEmail, _setupBusiness, cancellationToken).ConfigureAwait(true));
            var model = new DeleteCourseMessage();
            model.Message = task.Message;
            model.Success = task.Connected;
            return View(model);
        }

        [HttpPost]
        public async Task<string> DeleteCourse(string id, CancellationToken cancellationToken)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var gcEmail = _setupBusiness.GetClientEmail(lea);
            if (string.IsNullOrWhiteSpace(gcEmail))
            {
                return "Google Classroom setup not completed";
            }

            var syncMessage = new SyncCourseMessage { Courses = new List<GcCourse> { new GcCourse { CourseId = id } }, LeaId = lea, UserEmail = gcEmail };

            var task = await Task.Run(async () => await GcSync.DeleteCourses(this, _setupBusiness, syncMessage, cancellationToken).ConfigureAwait(true));
            _provisioningRuleBusiness.SaveLog(task.Logs);

            return task.Message;
        }

        [HttpPost]
        public async Task<JsonResult> DeleteAll(List<string> ids, CancellationToken cancellationToken)
        {
            var lea = _sessionInfo.CurrentAgencyId.GetValueOrDefault();
            var gcEmail = _setupBusiness.GetClientEmail(lea);
            if (string.IsNullOrWhiteSpace(gcEmail))
            {
                return Json("Google Classroom setup not completed");
            }
            var syncMessage = new SyncCourseMessage { Courses = ids.Select(i=> new GcCourse { CourseId = i }).ToList(), LeaId = lea, UserEmail = gcEmail };

            var task = await Task.Run(async () => await GcSync.DeleteCourses(this, _setupBusiness, syncMessage, cancellationToken).ConfigureAwait(true));

WISEroster.Mvc/Views/Sync/Existing.cshtml
@model WISEroster.Mvc.Models.DeleteCourseMessage

<br />
<div class="row">
    <div class="col">
        <div class="card bg-light">
            <div class="card-header bg-secondary text-white">
                <b>Existing Google Classes</b>
            </div>
            <div class="card-body">
                <div id="testConnection" class="h5">@Model.Message</div>
                <div id="ruleListGridDiv">
                    <table id="rulesList" class="table table-condensed table-bordered" width="100%">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Section</th>
                                <th>Created</th>
                                <th>Owner</th>
                                <th>State</th>
                                <th>Id</th>
                                <th>
                                    <div id="buttonDiv">
                                        <button type="button" id="deleteAll" class="btn-primary">Delete All Courses</button></div>

                                        <div id="spinnerDiv"><span>Deleting... this might take a while.</span><div class="loader" id="syncSpinner"></div></div>
                                </th>
                            </tr>
                        </thead>
                        <tfoot>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <script type="text/javascript">
        $("#spinnerDiv").hide();
        var rulesListTable;
        var myTimer;


        $(document).ready(function() {
            rulesList();

        });

        function rulesList() {
            rulesListTable = $('#rulesList').DataTable({
                ajax: {
                    url: "@Url.Action("GcList", "Sync")",
                    type: "POST",
                    datatype: "json",
                    dataSrc: ""
                },
                columns: [
                    { data: "Name" },
                    { data: "Section" },
                    {
                        data: "CreationTime",
                        render: function(data) {
                            return moment(data).format("YYYY-MM-DD HH:mm:ss.SSS");
                        }
                    },
                    { data: "OwnerId" },
                    { data: "CourseState" },
                    { data: "Id" },
                    {
                        orderable: false,
                        data: "Id",
                        render: function (data) {
                            return '<span id="sp' +
                                data +
                                '"><button class="ruleDelete btn-primary" data-id="' +
                                data +
                                '">Delete</button></span>';
                        }
                    }
                ],
                searching: false,
                paging: false,
                info: false
            });

        $('#rulesList tbody').on('click',
            '.ruleDelete',
            function() {
                var ruleId = $(this).data("id");
                $.ajax({
                    url: "@Url.Action("DeleteCourse", "Sync")",
                    type: 'POST',
                    datatype: 'JSON',
                    data: { id: ruleId },
                    success:
                        function (data) {
                            $("#sp"+ruleId).html(data);
                        }
                });
            });
        }

        $("#deleteAll").on("click",
            function () {
                syncStart();
               var ids = [];
                for (var i = 0; i < rulesListTable.data().length ;i++){
                   ids[i] = rulesListTable.data()[i].Id;
                }
                $.ajax({
                    url: "@Url.Action("DeleteAll", "Sync")",
                    type: 'POST',
                    datatype: 'JSON',
                    data: { ids: ids },
                    complete: function(data) { syncDone(data.Message); }
                });
            });

        function syncStart() {
            $("#spinnerDiv").show();
            $("#buttonDiv").hide();
            myTimer = setTimeout(keepAlive, 20000);
        }

        function keepAlive() {
            //keep process awake
            $.ajax({
                url: "@Url.Action("KeepAlive")",
                type: 'POST'
            });
        }

        function syncDone(message) {
            $("#spinnerDiv").hide();
            $("#buttonDiv").show();
            $("#testConnection").html(message);
            clearTimeout(myTimer);
            rulesListReload();
        }

        function rulesListReload() {
            rulesListTable.ajax.reload();
        }
    </script>
}

WISEroster.Mvc/Views/Sync/Preview.cshtml
@model WISEroster.Mvc.Models.SyncViewModel

<br />

        <div class="row">
            <ol>
                <li>Generate Sync List: Saves a working list of courses to be sent to Google Classroom.</li>
                <li>Sync Courses: Saves classes and invites teachers and students and logs the corresponding IDs.  This only adds classes and invites teachers and students.  No deletes occur.</li>
                <li>Activate Courses: Makes the classes available/visible for teachers and students.</li>
                <li>In Google Classroom: The Teacher must Accept the course in Google Classroom.</li>
                <li>Transfer Ownership: Issue an invitation for a teacher to own the class in Google Classroom.  This will only work if a single teacher (other than the administrator) is added to the class.</li>
                <li>In GMail: The Teacher must Accept the invitation to own in Google Classroom.</li>
            </ol>


</div>

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header bg-secondary text-white">
                <b>Sync For</b>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Generate", "Sync", FormMethod.Post, new { id = "ruleForm" }))
                {
                    <div class="row">
                        <div class="col-sm-4">
                            <div>@Html.LabelFor(m => m.SchoolYear)<span class="fa fa-asterisk text-danger"></span></div>
                            <div>@Html.DropDownListFor(m => m.SchoolYear, Model.Years, new { id = "SchoolYear", style = "width:300px" })</div>
                            <div class="text-danger">@Html.ValidationMessageFor(model => model.SchoolYear)</div>
                        </div>
                        <div class="col-sm-6">
                            <div>@Html.LabelFor(m => m.SelectedSchool)<span class="fa fa-asterisk text-danger"></span></div>
                            <div>@Html.DropDownListFor(m => m.SelectedSchool, Model.Schools, new { id = "SchoolId", style = "width:300px", onchange = "rulesListReload();" })</div>
                            <div class="text-danger">@Html.ValidationMessageFor(model => model.SelectedSchool)</div>
                        </div>
                        <div class="col-md-2"><button type="submit" id="saveButton" class="btn-primary">Generate Sync List</button></div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col">
        <div class="card bg-light">
            <div class="card-header bg-secondary text-white">
                <b>Classroom Sync List</b>
            </div>
            <div class="card-body">
              
                <div class="row">
                    <div class="col-md-4"> <span id="testConnection" class="h5"></span><br/> <span id="existingClasses"></span></div>
                    <div class="col-md-4" id="buttonDiv">
                        <button type="button" id="syncButton" class="btn-primary">Sync Courses</button>
                        <button type="button" id="activateButton" class="btn-primary">Activate Courses</button>
                        <button type="button" id="transferButton" class="btn-primary">Transfer Course Ownership</button>
                    </div>
                    <div class="col-md-4" id="spinnerDiv"><span>Sending data... this might take a while.</span>
                        <div class="loader" id="syncSpinner"></div></div>

                </div>
                <div id="ruleListGridDiv">
                    <table id="rulesList" class="table table-condensed table-bordered" width="100%">
                        <thead>
                        <tr>
                            <th width="20%">
                                <ol><li>Session Name</li>
                                    <li>Grade or Local Course Code</li>
                                    <li>Local Course Title</li>
                                    <li>Section Identifier</li></ol></th>
                            <th width="20%">GcName / Include For Sync</th>
                            <th>Staff</th>
                            <th>Students</th>
                            <th>Sync History</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts
{
    <script type="text/javascript">
        var rulesListTable;
        var myTimer;

        function filter() {
            return { schoolYear: $("#SchoolYear").val(), schoolId: $("#SchoolId").val() };
        }

        $("#spinnerDiv").hide();
        $('#buttonDiv').hide();
        $(document).ready(function() {
            @if (Model.Schools.Any())
            {
                @:rulesList();
            }
            $.get("@Url.Action("TestConnection")",
                function(data) {
                    if (!data.Connected) {
                        $('#buttonDiv').hide();
                    } else {
                        $('#buttonDiv').show();
                        $("#existingClasses").html('@Html.ActionLink("Classroom List", "Existing")');
                    }
                    $("#testConnection").html(data.Message);
                });

        });

        function rulesList() {
            rulesListTable = $('#rulesList').DataTable({
                ajax: {
                    url: "@Url.Action("ClassList", "Sync")",
                    type: "POST",
                    datatype: "json",
                    data: function(d) {
                        return filter();
                    },
                    dataSrc: ""
                },
                columns: [
                    {
                        data: null,
                        render: function(data) {
                            return "<ol><li>" +
                                data.SessionName +
                                "</li><li>" +
                                data.LocalCourseCode +
                                "</li><li>" +
                                data.LocalCourseTitle +
                                "</li><li>" +
                                data.LocalCourseCode +
                                "</li></ol>";
                        }
                    },
                    {
                        data: null,
                        render: function(data) {
                            return data.GcName + " / " + moment(data.CreateDate).format("YYYY-MM-DD HH:mm:ss.SSS");
                        }
                    },
                    {
                        orderable: false,
                        data: "Staff",
                        defaultContent: ''
                    },
                    {
                        orderable: false,
                        data: "Student",
                        defaultContent: ''
                    },
                    {
                        data: "GcMessage"
                    },
                    {
                        orderable: false,
                        data: null,
                        render: function(data) {
                            return ('<span id="sp' +
                                    data.GcName +
                                    '"><button class="classSync btn-primary" data-id="' +
                                    data.GcName +
                                    '">Sync</button></span>') +
                                (data.Saved 
                                    ? ' <span id="a' +
                                    data.GcName +
                                    '"><button class="classActivate btn-primary" data-id="' +
                                    data.GcName +
                                    '">Activate</button></span>'
                                    : ''
                                ) +
                                (data.Saved && data.Activated
                                    ? ' <span id="a' +
                                    data.GcName +
                                    '"><button class="classTransfer btn-primary" data-id="' +
                                    data.GcName +
                                    '">Transfer</button></span>'
                                    : ''
                                );
                        }
                    }
                ],
                searching: false,
                paging: false,
                info: false
            });


            $('#rulesList tbody').on('click',
                '.classSync',
                function() {
                    var ruleId = $(this).data("id");
                    $.ajax({
                        url: "@Url.Action("SendSelectedCourse", "Sync")",
                        type: 'POST',
                        datatype: 'JSON',
                        data: {
                            schoolYear: $("#SchoolYear").val(),
                            schoolId: $("#SchoolId").val(),
                            classToSync: ruleId
                        },
                        success:
                            function(data) {
                                $(document.getElementById("sp" + ruleId)).html(data);
                            }
                    });
                });

            $('#rulesList tbody').on('click',
                '.classActivate',
                function() {
                    var id = $(this).data("id");
                    $.ajax({
                        url: "@Url.Action("ActivateCourse", "Sync")",
                        type: 'POST',
                        datatype: 'JSON',
                        data: { schoolYear: $("#SchoolYear").val(), schoolId: $("#SchoolId").val(), id: id },
                        success:
                            function(data) {
                                $(document.getElementById("a" + id)).html(data);
                            }
                    });
                });

            $('#rulesList tbody').on('click',
                '.classTransfer',
                function() {
                    var id = $(this).data("id");
                    $.ajax({
                        url: "@Url.Action("SendInvite", "Sync")",
                        type: 'POST',
                        datatype: 'JSON',
                        data: { schoolYear: $("#SchoolYear").val(), schoolId: $("#SchoolId").val(), id: id },
                        success:
                            function(data) {
                                $(document.getElementById("a" + id)).html(data);
                            }
                    });
                });
        }


        function rulesListReload() {
            rulesListTable.ajax.reload();
        }

        $("#SchoolYear").on("change",
            function() {
                UpdateOptions('@Url.Action("FilterSchools", "Home")',
                    $("#ruleForm").serialize(),
                    "#SchoolId",
                    "");
                $("#SchoolId").trigger("change");
                rulesListTable.ajax.reload();
            });

        $("#syncButton").on("click",
            function() {
                syncStart();
                $.ajax({
                    url: "@Url.Action("SendCourses")",
                    type: 'POST',
                    datatype: 'JSON',
                    data: filter(),
                    complete: function(data) { syncDone(data); }
                });
            });
      

        $("#activateButton").on("click",
            function() {
                syncStart();
                $.ajax({
                    url: "@Url.Action("SendCourseActivations")",
                    type: 'POST',
                    datatype: 'JSON',
                    data: filter(),
                    complete: function(data) { syncDone(data); }
                });
            });

        $("#transferButton").on("click",
            function() {
                syncStart();
                $.ajax({
                    url: "@Url.Action("SendOwnerInvitations")",
                    type: 'POST',
                    datatype: 'JSON',
                    data: filter(),
                    complete: function(data) { syncDone(data); }
                });
            });

        function syncStart() {
            $("#spinnerDiv").show();
            $("#buttonDiv").hide();
            myTimer = setTimeout(keepAlive, 20000);
        }

        function keepAlive() {
            //keep process awake
            $.ajax({
                url: "@Url.Action("KeepAlive")",
                type: 'POST'
            });
        }



        function syncDone(data) {
            $("#spinnerDiv").hide();
            $("#buttonDiv").show();
            if (data.Message) {
                $("#testConnection").html(data.Message);
            }
            clearTimeout(myTimer);
            rulesListReload();
        }
    </script>
}